gamaleiloes/urls.py
# myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),  
    path('admin/', include('admin_custom.urls')),
    path('categories/', include('categories.urls')),
    path('accounts/', include('user_management.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
# pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='home'),
    path('como-participar/', views.como_participar, name='como_participar'),
    path('leiloes_ao_vivo/', views.leiloes_ao_vivo, name='leiloes_ao_vivo'),
    path('calendario/', views.calendario, name='calendario'),
    path('leilao/<str:codigo_leilao>/<str:codigo_item>/', views.item_details, name='item_details'),
    path('leilao/<str:codigo_leilao>/ao-vivo', views.ao_vivo, name='ao_vivo'),
    path('leilao/<str:codigo_leilao>/', views.leilao_detalhe, name='leilao_detalhe'),
    path('dashboard/inicio/', views.inicio, name='inicio'),
    path('dashboard/lotes/', views.lotes, name='lotes'),
    path('dashboard/lances/', views.lances, name='lances'),
    path('financeiro/', views.financeiro_cliente, name='financeiro_cliente'),
    path('lance/<str:codigo_leilao>/<str:codigo_item>/', views.create_bid, name='create_bid'),
]

user_management/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('profile/', views.profile_view, name='account_profile'),
    path('profile/details/', views.profile_details, name='account_profile_details'),
    path('profile/edit/', views.edit_profile, name='account_edit_profile'),
    path('profile/leiloes/', views.leiloes_view, name='account_leilao'),  # Página de Leilões
    path('profile/lances/', views.lances_view, name='account_lance'),  # Página de Lances
    path('profile/financeiro/', views.financeiro_view, name='account_financeiro'),  # Página Financeiro
    path('profile/documentos/', views.documentos_view, name='account_documentos'),  # Página Documentos
    path('documentos/<int:documento_id>/', views.serve_documento, name='serve_documento'),
    path('', include('allauth.urls')),
]

user_management/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from django.core.files.storage import FileSystemStorage

# Adicione constantes para tipos de usuário
USER_TYPE_CHOICES = [
    ('arrematante', 'Arrematante'),
    ('admin', 'Admin'),
    ('default', 'Default'),
]

# Adicione o campo ao modelo User
User.add_to_class('user_type', models.CharField(
    max_length=15, choices=USER_TYPE_CHOICES, default='default'
))

class Documento(models.Model):
    TIPO_DOCUMENTO_CHOICES = [
        ('RG', 'RG'),
        ('CNH', 'CNH'),
        ('PASSAPORTE', 'Passaporte'),
        ('COMPROVANTE_RESIDENCIA', 'Comprovante de Residência'),
        ('CONTRATO_SOCIAL', 'Contrato Social'),
        ('SELFIE', 'Selfie'),  
    ]

    STATUS_CHOICES = [
        ('P', 'Pendente'),
        ('A', 'Aprovado'),
        ('R', 'Rejeitado'),
    ]

    arrematante = models.ForeignKey(
        'Arrematante', related_name='documentos', on_delete=models.CASCADE, null=True, blank=True
    )
    tipo_documento = models.CharField(max_length=50, choices=TIPO_DOCUMENTO_CHOICES)
    documento = models.FileField(upload_to='documentos/', storage=FileSystemStorage(location=settings.PROTECTED_DOCUMENTS_DIR), blank=False, null=False)
    data_upload = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='P')  # Campo de status

    def clean(self):
        # Verificar o tamanho máximo do arquivo (10 MB)
        max_file_size = 10 * 1024 * 1024
        if self.documento and self.documento.size > max_file_size:
            raise ValidationError("O tamanho do arquivo não pode exceder 10 MB.")
        
        # Verificar extensões permitidas
        valid_extensions = ['.pdf', '.jpg', '.png']
        if self.documento and not any(self.documento.name.endswith(ext) for ext in valid_extensions):
            raise ValidationError(f"Permitido apenas arquivos: {', '.join(valid_extensions)}")

    def clean_user_document(self):
        # Validar qual tipo de usuário está enviando o documento e garantir que os documentos sejam válidos
        if self.arrematante:
            if self.arrematante.tipo_cadastro == 'PF':
                if self.tipo_documento == 'COMPROVANTE_RESIDENCIA':
                    return  # Comprovante de Residência é permitido para PF
                elif self.tipo_documento not in ['RG', 'CNH', 'PASSAPORTE', 'SELFIE']:
                    raise ValidationError('Para Pessoa Física (PF), é necessário enviar RG, CNH, Passaporte, Comprovante de Residência ou Selfie.')
            elif self.arrematante.tipo_cadastro == 'PJ':
                if self.tipo_documento in ['COMPROVANTE_RESIDENCIA', 'CONTRATO_SOCIAL', 'SELFIE']:
                    return  # Comprovante de Residência, Contrato Social e Selfie são permitidos para PJ
                raise ValidationError('Para Pessoa Jurídica (PJ), é necessário enviar Contrato Social, Comprovante de Residência ou Selfie.')

    def save(self, *args, **kwargs):
        self.clean_user_document()  # Chama a validação do documento antes de salvar
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.get_tipo_documento_display()} - {self.arrematante.user.username}"

    class Meta:
        verbose_name = "Documento"
        verbose_name_plural = "Documentos"


class Arrematante(models.Model):
    TIPO_CADASTRO_CHOICES = [
        ('PF', 'Pessoa Física'),
        ('PJ', 'Pessoa Jurídica'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='arrematante')
    cpf_cnpj = models.CharField(max_length=30)
    cep = models.CharField(max_length=9)
    logradouro = models.CharField(max_length=255)
    numero = models.CharField(max_length=10)
    complemento = models.CharField(max_length=255, blank=True, null=True)
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=50)
    pais = models.CharField(max_length=50)
    telefone_comercial = models.CharField(max_length=15, blank=True, null=True)
    telefone_celular = models.CharField(max_length=15)

    tipo_cadastro = models.CharField(
        max_length=2,
        choices=TIPO_CADASTRO_CHOICES,
    )

    documentos_enviados = models.BooleanField(default=False)

    @property
    def pode_dar_lance(self):
        return self.documentos_enviados 

    def __str__(self):
        return f"{self.user.username} - {self.get_tipo_cadastro_display()}"

    class Meta:
        verbose_name = "Arrematante"
        verbose_name_plural = "Arrematantes"


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="admin")
    setor = models.CharField(max_length=100, verbose_name="Setor")
    telefone = models.CharField(max_length=15, verbose_name="Telefone de Contato")

    def __str__(self):
        return f"Admin: {self.user.username}"

    class Meta:
        verbose_name = "Admin"
        verbose_name_plural = "Admins"



# Sinal para criar perfis automaticamente após a criação de um usuário
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        # Criar perfil de Arrematante como padrão
        if not hasattr(instance, "arrematante"):
            Arrematante.objects.create(
                user=instance,
                cpf_cnpj='',
                cep='',
                logradouro='',
                numero='',
                complemento='',
                bairro='',
                cidade='',
                estado='',
                pais='',
                telefone_comercial='',
                telefone_celular='',
                tipo_cadastro='PF',  # Tipo padrão Pessoa Física
            )

        # Caso específico: criar perfil de Admin (se necessário, baseado em lógica adicional)
        if not hasattr(instance, "admin"):
            Admin.objects.create(
                user=instance,
                setor='',  # Dados padrão
                telefone='',  # Dados padrão
            )

    # Atualiza o campo user_type, garantindo que o sinal não cause um loop
    user_type = 'default'  # Valor padrão
    if hasattr(instance, "arrematante"):
        user_type = 'arrematante'
    elif hasattr(instance, "admin"):
        user_type = 'admin'

    if instance.user_type != user_type:  # Apenas salva se houver mudança
        instance.user_type = user_type
        instance.save(update_fields=["user_type"])

user_management/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import CustomSignupForm, ArrematanteEditForm, UserEditForm
from allauth.account.forms import LoginForm
from django.contrib.auth.decorators import login_required
from .models import Arrematante, Documento
from .forms import DocumentoForm
from django.conf import settings
from django.http import HttpResponse, Http404
import os

def custom_login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        form.login(request)
        return redirect('home')  # Redireciona após login bem-sucedido
    return render(request, 'account/login.html', {'form': form})


def signup_view(request):
    if request.method == 'POST':
        form = CustomSignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Faz login automático após cadastro
            return redirect('home')  # Redireciona para a página inicial
        else:
            return render(request, 'signup.html', {'form': form})
    else:
        form = CustomSignupForm()
    return render(request, 'signup.html', {'form': form})


def profile_view(request):
    documentos_pendentes = []

    if request.user.is_authenticated:
        arrematante = request.user.arrematante

        if arrematante.tipo_cadastro == 'PF':
            if not arrematante.documentos.filter(tipo_documento='RG').exists():
                if not arrematante.documentos.filter(tipo_documento='CNH').exists():
                    if not arrematante.documentos.filter(tipo_documento='PASSAPORTE').exists():
                        documentos_pendentes.append('Identidade (RG, CNH ou Passaporte)')
                
            if not arrematante.documentos.filter(tipo_documento='COMPROVANTE_RESIDENCIA').exists():
                documentos_pendentes.append('Comprovante de residência')
            if not arrematante.documentos.filter(tipo_documento='SELFIE').exists():
                documentos_pendentes.append('Selfie')

        elif arrematante.tipo_cadastro == 'PJ':
            if not arrematante.documentos.filter(tipo_documento='CONTRATO_SOCIAL').exists():
                documentos_pendentes.append('Contrato Social')
            if not arrematante.documentos.filter(tipo_documento='COMPROVANTE_RESIDENCIA').exists():
                documentos_pendentes.append('Comprovante de residência')
            if not arrematante.documentos.filter(tipo_documento='SELFIE').exists():
                documentos_pendentes.append('Selfie')

    return render(request, 'accounts/profile.html', {
        'documentos_pendentes': documentos_pendentes,
    })


@login_required
def profile_details(request):
    """
    Detalhes do perfil do usuário.
    """
    try:
        arrematante = request.user.arrematante
    except Arrematante.DoesNotExist:
        arrematante = None

    return render(request, 'accounts/profile_details.html', {
        'arrematante': arrematante,
    })


@login_required
def edit_profile(request):
    """
    Permite que o usuário edite seu perfil e suas informações pessoais.
    """
    try:
        arrematante = request.user.arrematante
    except Arrematante.DoesNotExist:
        return redirect('profile')  # Redireciona caso o perfil não exista

    if request.method == 'POST':
        profile_form = ArrematanteEditForm(request.POST, instance=arrematante)
        user_form = UserEditForm(request.POST, instance=request.user)

        if profile_form.is_valid() and user_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('account_profile')
    else:
        profile_form = ArrematanteEditForm(instance=arrematante)
        user_form = UserEditForm(instance=request.user)

    return render(request, 'accounts/edit_profile.html', {
        'profile_form': profile_form,
        'user_form': user_form,
    })


@login_required
def leiloes_view(request):
    """
    Exibe os leilões do usuário.
    """
    try:
        arrematante = request.user.arrematante  # Obtém o arrematante
        leiloes = arrematante.leiloes.all()  # Supondo que o arrematante tenha uma relação com leilões
    except Arrematante.DoesNotExist:
        leiloes = []  # Caso não haja arrematante, retorna uma lista vazia

    return render(request, 'accounts/leiloes.html', {
        'leiloes': leiloes,
    })


@login_required
def lances_view(request):
    """
    Exibe os lances feitos pelo usuário.
    """
    try:
        arrematante = request.user.arrematante
        lances = arrematante.lances.all()  # Supondo que o arrematante tenha uma relação com lances
    except Arrematante.DoesNotExist:
        lances = []  # Caso não haja arrematante, retorna uma lista vazia

    return render(request, 'accounts/lances.html', {
        'lances': lances,
    })


@login_required
def serve_documento(request, documento_id):
    try:
        documento = Documento.objects.get(id=documento_id)
    except Documento.DoesNotExist:
        raise Http404("Documento não encontrado.")
    
    # Verifique se o usuário autenticado é o usuário associado ao arrematante do documento
    if documento.arrematante.user != request.user:
        raise Http404("Você não tem permissão para acessar este documento.")
    
    # Caminho para o arquivo
    file_path = os.path.join(settings.PROTECTED_DOCUMENTS_DIR, documento.documento.name)
    
    # Verifique se o arquivo realmente existe
    if not os.path.exists(file_path):
        raise Http404("Arquivo não encontrado.")
    
    # Servir o arquivo
    with open(file_path, 'rb') as f:
        return HttpResponse(f.read(), content_type="application/pdf")


@login_required
def documentos_view(request):
    user = request.user
    arrematante = user.arrematante if hasattr(user, 'arrematante') else None
    
    # Defina os tipos de documentos permitidos com base no tipo de arrematante
    if arrematante and arrematante.tipo_cadastro == 'PF':
        tipos_documentos_permitidos = ['RG', 'CNH', 'PASSAPORTE', 'SELFIE', 'COMPROVANTE_RESIDENCIA']
    elif arrematante and arrematante.tipo_cadastro == 'PJ':
        tipos_documentos_permitidos = ['COMPROVANTE_RESIDENCIA', 'CONTRATO_SOCIAL', 'SELFIE']
    else:
        tipos_documentos_permitidos = []

    # Obtenha os documentos do arrematante
    documentos = Documento.objects.filter(arrematante=arrematante)

    if request.method == 'POST':
        form = DocumentoForm(request.POST, request.FILES)
        if form.is_valid():
            documento = form.save(commit=False)
            # Verifica se há documentos anteriores
            documentos_existentes = Documento.objects.filter(arrematante=arrematante, tipo_documento=documento.tipo_documento)
            for doc in documentos_existentes:
                if doc.status == 'P':  # Se houver documento pendente, não permita o envio
                    return render(request, 'accounts/documentos.html', {
                        'form': form,
                        'documentos': documentos,
                        'tipos_documentos_permitidos': tipos_documentos_permitidos,
                        'arrematante': arrematante,
                        'erro': 'Você já possui um documento pendente para esse tipo.',
                    })
            documento.arrematante = arrematante
            documento.save()
            return redirect('account_documentos')  # Redirecionar após o envio do documento
    else:
        form = DocumentoForm()

    return render(request, 'accounts/documentos.html', {
        'documentos': documentos,
        'tipos_documentos_permitidos': tipos_documentos_permitidos,
        'arrematante': arrematante,
        'form': form,
    })


@login_required
def financeiro_view(request):
    """
    Exibe as informações financeiras do usuário.
    """
    try:
        arrematante = request.user.arrematante
        financeiro = arrematante.financeiro  # Supondo que o arrematante tenha uma relação com financeiro
    except Arrematante.DoesNotExist:
        financeiro = None  # Caso não haja arrematante, retorna None

    return render(request, 'accounts/financeiro.html', {
        'financeiro': financeiro,
    })

user_management/templates/accounts/documentos.html
{% extends "base.html" %}
{% load i18n custom_filters %}  <!-- Carregar o filtro customizado -->

{% block head_title %}
    {% trans "Meus Documentos" %}
{% endblock head_title %}

{% block content %}
    <div class="container form-container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-10">  <!-- Card maior -->
                <div class="card shadow-sm rounded-lg">
                    <div class="card-body">
                        <h2 class="text-center text-primary mb-4">{% trans "Meus Documentos" %}</h2>

                        {% if documentos %}
                            <h4>{% trans "Documentos Enviados" %}</h4>
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>{% trans "Tipo de Documento" %}</th>
                                        <th>{% trans "Arquivo" %}</th>
                                        <th>{% trans "Nome do Arquivo" %}</th>
                                        <th>{% trans "Status" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for documento in documentos %}
                                        <tr>
                                            <td>{{ documento.get_tipo_documento_display }}</td>
                                            <td><a href="{% url 'serve_documento' documento.id %}" target="_blank">{% trans "Ver Documento" %}</a></td>
                                            <td><small>{{ documento.documento.name|get_original_filename }}</small></td>  <!-- Nome do arquivo sem caminho e código -->
                                            <td>
                                                {% if documento.status == 'P' %}
                                                    <span class="badge bg-warning">{% trans "Pendente" %}</span>
                                                {% elif documento.status == 'A' %}
                                                    <span class="badge bg-success">{% trans "Aprovado" %}</span>
                                                {% elif documento.status == 'R' %}
                                                    <span class="badge bg-danger">{% trans "Rejeitado" %}</span>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <p>{% trans "Você ainda não enviou nenhum documento." %}</p>
                        {% endif %}

                        {% if documentos|length == 0 or documentos.last.status == 'R' or documentos.last.status == 'P' %}
                            <h4>{% trans "Enviar Novo Documento" %}</h4>

                            {% if form.tipo_documento.value %}
                                {% with form.tipo_documento.value as tipo_documento_selecionado %}
                                    {% if documentos %}
                                        {% for documento in documentos %}
                                            {% if documento.tipo_documento == tipo_documento_selecionado and documento.status != 'R' %}
                                                <div class="alert alert-danger">
                                                    {% trans "Você já enviou este documento e ele está pendente ou aprovado. Você só pode enviar um novo documento deste tipo se o anterior for rejeitado." %}
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                {% endwith %}
                            {% endif %}

                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}

                                <div class="form-group">
                                    <label for="id_tipo_documento">{% trans "Tipo de Documento" %}</label>
                                    <select name="tipo_documento" class="form-control" id="id_tipo_documento">
                                        {% for choice in form.tipo_documento.field.choices %}
                                            {% if choice.0 in tipos_documentos_permitidos %}
                                                <option value="{{ choice.0 }}" {% if form.tipo_documento.value == choice.0 %}selected{% endif %}>
                                                    {{ choice.1 }}
                                                </option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="id_documento">{% trans "Documento" %}</label>
                                    {{ form.documento }}
                                </div>

                                <button type="submit" class="btn btn-dark btn-block mt-3">{% trans "Enviar Documento" %}</button>
                            </form>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

user_management/templates/accounts/edit_profile.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}
{% include '_head.html' %}

<body>
    {% include '_header.html' %}

    <div class="container mt-5">
        <h2 class="h3">Editar Perfil</h2>

        <form method="POST" action="{% url 'account_edit_profile' %}">
            {% csrf_token %}
            
            <!-- Formulário para edição de informações do usuário (nome) -->
            <div class="form-group">
                <label for="first_name">Primeiro Nome</label>
                <input type="text" class="form-control" id="first_name" name="first_name" value="{{ user_form.instance.first_name }}" required>
            </div>
            <div class="form-group">
                <label for="last_name">Sobrenome</label>
                <input type="text" class="form-control" id="last_name" name="last_name" value="{{ user_form.instance.last_name }}" required>
            </div>

            <!-- Formulário para edição das informações do perfil -->
            <div class="form-group">
                <label for="telefone_celular">Telefone Celular</label>
                <input type="text" class="form-control" id="telefone_celular" name="telefone_celular" value="{{ profile_form.instance.telefone_celular }}">
            </div>
            <div class="form-group">
                <label for="cep">CEP</label>
                <input type="text" class="form-control" id="cep" name="cep" value="{{ profile_form.instance.cep }}">
            </div>
            <!-- Adicione mais campos de edição conforme necessário -->

            <button type="submit" class="btn btn-dark">Salvar Alterações</button>
        </form>
    </div>

    {% include '_footer.html' %}
</body>
</html>

user_management/templates/accounts/profile_details.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %} 
{% include '_head.html' %}

<body>
    {% include '_header.html' %}
    
    <div class="container mt-5">
        <h2 class="h3">Informações do Cadastro</h2>
        <ul class="list-group">
            <li class="list-group-item">Nome de usuário: {{ user.username }}</li>
            <li class="list-group-item">Nome completo: {{ user.first_name }} {{ user.last_name }}</li>
            <li class="list-group-item">E-mail: {{ user.email }}</li>
            <li class="list-group-item">Data de cadastro: {{ user.date_joined }}</li>

            {% if user.profile %}
            <li class="list-group-item">CPF/CNPJ: {{ user.profile.cpf_cnpj }}</li>
            <li class="list-group-item">Telefone Celular: {{ user.profile.telefone_celular }}</li>
            <li class="list-group-item">Telefone Comercial: {{ user.profile.telefone_comercial }}</li>
            <li class="list-group-item">CEP: {{ user.profile.cep }}</li>
            <li class="list-group-item">Logradouro: {{ user.profile.logradouro }}</li>
            <li class="list-group-item">Número: {{ user.profile.numero }}</li>
            <li class="list-group-item">Complemento: {{ user.profile.complemento }}</li>
            <li class="list-group-item">Bairro: {{ user.profile.bairro }}</li>
            <li class="list-group-item">Cidade: {{ user.profile.cidade }}</li>
            <li class="list-group-item">Estado: {{ user.profile.estado }}</li>
            <li class="list-group-item">País: {{ user.profile.pais }}</li>
            {% endif %}
        </ul>
    </div>

    {% include '_footer.html' %}
</body>
</html>