gamaleiloes/urls.py
# myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),  
    path('admin/', include('admin_custom.urls')),
    path('categories/', include('categories.urls')),
    path('accounts/', include('user_management.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
# pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='home'),
    path('como-participar/', views.como_participar, name='como_participar'),
    path('leiloes_ao_vivo/', views.leiloes_ao_vivo, name='leiloes_ao_vivo'),
    path('calendario/', views.calendario, name='calendario'),
    path('leilao/<str:codigo_leilao>/<str:codigo_item>/', views.item_details, name='item_details'),
    path('leilao/<str:codigo_leilao>/ao-vivo', views.ao_vivo, name='ao_vivo'),
    path('leilao/<str:codigo_leilao>/', views.leilao_detalhe, name='leilao_detalhe'),
    path('dashboard/inicio/', views.inicio, name='inicio'),
    path('dashboard/lotes/', views.lotes, name='lotes'),
    path('dashboard/lances/', views.lances, name='lances'),
    path('financeiro/', views.financeiro_cliente, name='financeiro_cliente'),
    path('lance/<str:codigo_leilao>/<str:codigo_item>/', views.create_bid, name='create_bid'),
]

pages/templates/pages/calendario.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %} 
{% include '_head.html' %}
<body>
    {% include '_header.html' %}

    <!-- Seção de Introdução -->
    <div class="container mt-5 text-center">
        <h1 class="display-4">Calendário de Leilões</h1>
        <p class="lead">Veja os leilões programados para este mês e clique para saber mais!</p>
    </div>

    <!-- Calendário de Leilões -->
    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table table-bordered text-center">
                        <thead class="thead-light">
                            <tr>
                                <th>Seg</th>
                                <th>Ter</th>
                                <th>Qua</th>
                                <th>Qui</th>
                                <th>Sex</th>
                                <th>Sab</th>
                                <th>Dom</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for week in calendar %}
                                <tr>
                                    {% for day in week %}
                                    <td>
                                        {% if day %}
                                            <div class="font-weight-bold">
                                                <span style='font-size: 15px;'>{{ day.day|date:"d" }} de {{ day.day|date:"F" }}</span>
                                            </div>
                                            <ul class="list-unstyled mt-2">
                                                {% for auction in day.auctions %}
                                                    <li>
                                                        <a href="{% url 'pages:leilao_detalhe' auction.codigo_leilao %}">
                                                            {{ auction.comitente }} - {{ auction.date_time|time:"H:i" }}
                                                        </a>
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                        {% endif %}
                                    </td>                                    
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {% include '_footer.html' %}
</body>
</html>

pages/templates/pages/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include '_head.html' %}
<body>
    {% include '_header.html' %}
    {% load index_filters %}

    <!-- Carrossel de Banners -->
    <div id="mainCarousel" class="carousel slide mb-5" data-bs-ride="carousel" data-bs-interval="5000" style="max-height: 400px; overflow: hidden;">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'pages/img/banner1.jpg' %}" class="d-block w-100" alt="Primeiro Banner" style="object-fit: cover;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Bem-vindo aos Leilões Inovadores</h5>
                    <p>Descubra oportunidades únicas em nosso marketplace.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'pages/img/banner2.jpg' %}" class="d-block w-100" alt="Segundo Banner" style="object-fit: cover;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Leilões Exclusivos</h5>
                    <p>Arte, antiguidades e muito mais em um só lugar.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'pages/img/banner3.jpg' %}" class="d-block w-100" alt="Terceiro Banner" style="object-fit: cover;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Participe Agora</h5>
                    <p>Não perca os leilões ao vivo mais emocionantes.</p>
                </div>
            </div>
        </div>
        <!-- Botões de Navegação -->
        <button class="carousel-control-prev custom-arrow" type="button" data-bs-target="#mainCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </button>
        <button class="carousel-control-next custom-arrow" type="button" data-bs-target="#mainCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </button>
    </div>

    <div class="container mt-5">
        <!-- Seção de Introdução -->
        <div class="row align-items-center main-section full-width">
            <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
                <span class="d-block text-secondary">Leilões Inovadores</span>
                <h1 class="display-4">Descubra Oportunidades Únicas em Leilões Ao Vivo</h1>
                <p class="lead">Participe de leilões emocionantes com segurança e transparência.</p>
                <a href="#" class="btn btn-outline-secondary btn-lg">Participe Agora</a>
            </div>
            <div class="col-md-6">
                <img src="{% static 'pages/img/pexels-photo-5668473.jpeg' %}" alt="Leilões" class="img-fluid">
            </div>
        </div>
    </div>

    <!-- Seção de Itens em Destaque -->
    <div class="central-section mb-5">
        <div class="container">
            <!-- Loop para as categorias de itens em destaque -->
            {% for categoria, itens in itens_destacados.items %}
                <h2 class="text-center mb-4">{{ categoria|replace_underscore }} em Destaque</h2>
                <div class="row">
                    {% if itens %}
                        {% for item in itens %}
                            <div class="col-12 col-md-4 mb-4">
                                <div class="card">
                                    <img src="{{ item.thumbnail.url }}" alt="{{ item.nome }}" class="card-img-top" style="height: 250px; object-fit: cover;">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ item.nome }}</h5>
                                        <p class="card-text">{{ item.descricao }}</p>
                                        <p>Valor avaliado: <strong>R$ {{ item.valor_avaliado }}</strong></p>
                                        <p>Status: {{ item.get_status_lote_display }}</p>
                                        <p>Data: {{ item.leilao.date_time|date:"d/m/Y" }}</p>
                                        <a href="{% url 'pages:item_details' item.leilao.codigo_leilao item.codigo_item %}" class="btn btn-secundario">Ver mais</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p class="text-center">Não há itens em destaque nesta categoria.</p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>

    {% include '_footer.html' %}
</body>
</html>

pages/templates/pages/item_details.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}
{% include '_head.html' %}
<body>
    {% include '_header.html' %}

    <!-- Seção de Detalhes do Item -->
    <div class="container mt-5">
        <!-- Título -->
        <div class="text-center mb-5">
            <h1 class="display-4 text-primario">Detalhes do Item</h1>
            <p class="lead text-muted">{{ item.nome }}</p>
        </div>

        <!-- Imagens e Informações -->
        <div class="row">
            <!-- Carrossel de Imagens -->
            <div class="col-lg-6">
                <div id="itemImagesCarousel" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        {% if item.thumbnail %}
                            <div class="carousel-item active">
                                <img src="{{ item.thumbnail.url }}" class="d-block w-100 rounded shadow-lg" alt="Imagem principal do item">
                            </div>
                        {% else %}
                            <div class="carousel-item active">
                                <img src="{% static 'images/default_item.jpg' %}" class="d-block w-100 rounded shadow-lg" alt="Imagem padrão">
                            </div>
                        {% endif %}
                        
                        {% for imagem in images %}
                            <div class="carousel-item">
                                <img src="{{ imagem.imagem.url }}" class="d-block w-100 rounded shadow-lg" alt="Imagem adicional do item">
                            </div>
                        {% empty %}
                            <div class="carousel-item active">
                                <img src="{% static 'images/default_item.jpg' %}" class="d-block w-100 rounded shadow-lg" alt="Imagem padrão">
                            </div>
                        {% endfor %}
                    </div>

                   <!-- Botões de navegação do carrossel -->
                   <button class="carousel-control-prev" type="button" data-bs-target="#itemImagesCarousel" data-bs-slide="prev" style="background: transparent; border: none;">
                    <span class="carousel-control-prev-icon" aria-hidden="true" style="filter: opacity(0.5);"><</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#itemImagesCarousel" data-bs-slide="next" style="background: transparent; border: none;">
                    <span class="carousel-control-next-icon" aria-hidden="true" style="filter: opacity(0.5);">></span>
                </button>
                </div>

                <!-- Formulário de Lance -->
                <div class="mt-4">
                    {% if not request.user.arrematante.pode_dar_lance %}
                        <div class="alert alert-warning" role="alert">
                            Você não pode dar lances até enviar todos os documentos necessários.
                        </div>
                    {% endif %}
                    <form method="POST" action="{% url 'pages:create_bid' leilao.codigo_leilao item.codigo_item %}">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="number" step="0.01" 
                                min="{% if highest_bid %}{{ highest_bid.amount|floatformat:2 }}{% else %}{{ item.valor_inicial|floatformat:2 }}{% endif %}" 
                                class="form-control" name="valor_lance" placeholder="Insira o valor do lance" required>
                            <button class="btn btn-primary" type="submit" {% if not request.user.arrematante.pode_dar_lance %}disabled{% endif %}>Enviar Lance</button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Detalhes do Item -->
            <div class="col-lg-6">
                <div class="card p-4 shadow-lg border-light">
                    <h3 class="text-primario mb-3">Informações do Item</h3>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>Descrição:</strong> {{ item.descricao }}</li>
                        <li class="list-group-item"><strong>Valor Inicial:</strong> R$ {{ item.valor_inicial|floatformat:2 }}</li>
                        <li class="list-group-item"><strong>Valor Avaliado:</strong> R$ {{ item.valor_avaliado|floatformat:2 }}</li>
                        <li class="list-group-item"><strong>Status do Lote:</strong> {{ item.status_lote }}</li>
                        <li class="list-group-item"><strong>Status de Pagamento:</strong> {{ item.status_pagamento }}</li>
                    </ul>
                    
                    <div class="mt-4">
                        <p><strong>Maior lance:</strong> 
                            {% if highest_bid %}
                                R$ {{ highest_bid.amount|floatformat:2 }}
                            {% else %}
                                Nenhum lance ainda
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Detalhes do Leilão e Timer -->
        <div class="row mt-5">
            <div class="col-lg-12">
                <div class="card p-4 shadow-lg border-light">
                    <h4 class="text-primario">Leilão</h4>
                    <p class="lead">Data do Leilão: {{ leilao_data|date:"d de F de Y às H:i" }}</p>
                    <div id="countdown" class="fs-4 mb-3"></div>

                    <!-- Botão para entrar no leilão ao vivo -->
                    <div id="liveAuctionBtn" style="display: none;">
                        <a href="{% url 'pages:leilao_detalhe' leilao.codigo_leilao %}" class="btn btn-success btn-lg">Entrar no Leilão ao Vivo</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Detalhes Específicos -->
        <div class="mt-5">
            <div>
                {% if item_type == 'Vehicle' %}
                    <h4 class="text-primario">Detalhes do Veículo</h4>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Marca:</strong> {{ item.marca }}</li>
                        <li class="list-group-item"><strong>Modelo:</strong> {{ item.modelo }}</li>
                        <li class="list-group-item"><strong>Ano de Fabricação:</strong> {{ item.fabricacao }}</li>
                        <li class="list-group-item"><strong>Categoria:</strong> {{ item.categoria_veiculo }}</li>
                        <li class="list-group-item"><strong>FIPE:</strong> R$ {{ item.fipe|floatformat:2 }}</li>
                        <li class="list-group-item"><strong>Versão:</strong> {{ item.versao }}</li>
                        <li class="list-group-item"><strong>Condicionamento:</strong> {{ item.condicao_funcionamento }}</li>
                        <li class="list-group-item"><strong>Combustível:</strong> {{ item.combustivel }}</li>
                    </ul>
                {% elif item_type == 'RealEstate' %}
                    <h4 class="text-primario">Detalhes do Imóvel</h4>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Localização:</strong> {{ item.localizacao }}</li>
                        <li class="list-group-item"><strong>Estado do Imóvel:</strong> {{ item.estado_imovel }}</li>
                        <li class="list-group-item"><strong>Quartos:</strong> {{ item.quartos }}</li>
                        <li class="list-group-item"><strong>Metragem:</strong> {{ item.metragem }} m²</li>
                    </ul>
                {% elif item_type == 'Rural' %}
                    <h4 class="text-primario">Detalhes do Item Rural</h4>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Origem:</strong> {{ item.origem }}</li>
                    </ul>
                {% elif item_type == 'OtherGoods' %}
                    <h4 class="text-primario">Detalhes de Outros Bens</h4>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Informações adicionais:</strong> Nenhum detalhe específico disponível.</li>
                    </ul>
                {% else %}
                    <h4 class="text-primario">Outras Informações</h4>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Detalhes adicionais:</strong> Nenhum detalhe específico disponível.</li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>

    {% include '_footer.html' %}

    <script>
        const countdownElement = document.getElementById('countdown');
        const liveAuctionBtn = document.getElementById('liveAuctionBtn');
        const targetDate = new Date("{{ leilao_data|date:'Y-m-d H:i:s' }}");

        function updateCountdown() {
            const now = new Date();
            const diff = targetDate - now;

            if (diff <= 0) {
                countdownElement.textContent = "Leilão iniciado!";
                liveAuctionBtn.style.display = 'block';  // Exibe o botão para entrar no leilão
                clearInterval(countdownInterval); // Para o intervalo após início
                return;
            }

            const days = Math.floor(diff / (1000 * 60 * 60 * 24));
            const hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
            const seconds = Math.floor((diff % (1000 * 60)) / 1000);

            countdownElement.textContent = `${days}d ${hours}h ${minutes}m ${seconds}s`;
        }

        const countdownInterval = setInterval(updateCountdown, 1000); // Chama a função a cada 1 segundo
        updateCountdown(); // Atualiza imediatamente ao carregar
    </script>
</body>
</html>

pages/templates/pages/item_not_found.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include '_head.html' %}
<body>
    {% include '_header.html' %}
    <div class="container mt-5 mb-5 p-4">
        <div class="row">
            <div class="col-12 text-center">
                <h1>Oops! Item Não Encontrado</h1>
                <p>Desculpe, o item que você está procurando não foi encontrado.</p>
                <p>Por favor, verifique o código do item ou retorne à página inicial.</p>
                <a href="{% url 'pages:home' %}" class="btn btn-primario">Voltar para a Página Inicial</a>
            </div>
        </div>
    </div>
    {% include '_footer.html' %}
</body>
</html>

pages/templates/pages/leilao_detalhe.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}
{% include '_head.html' %}
<body>
    {% include '_header.html' %}

    <!-- Seção de Detalhes do Leilão -->
    <div class="container mt-5">
        <div class="text-center mb-5">
            <h1 class="display-4">Detalhes do Leilão: {{ leilao.codigo_leilao }}</h1>
            <p class="lead">{{ leilao.descricao }}</p>
        </div>

        <div class="row mt-4">
            <div class="col-md-6">
                <h3>Informações do Leilão</h3>
                <ul class="list-unstyled">
                    <li><strong>Data:</strong> {{ leilao.date_time|date:"d/m/Y" }}</li>
                    <li><strong>Hora:</strong> {{ leilao.date_time|time:"H:i" }}</li>
                    <li><strong>Comitente:</strong> {{ leilao.comitente }}</li>
                    <li><strong>Categoria:</strong> {{ leilao.categoria }}</li>
                    <li><strong>Descrição:</strong> {{ leilao.descricao }}</li>
                    <li><strong>Quantidade de Lotes:</strong> {{ leilao.quantidade_lotes }}</li>
                    <li><strong>Status:</strong> 
                        {% if leilao.is_live %}
                            <span class="badge bg-success">Ao vivo</span>
                        {% elif leilao.is_scheduled_for_today %}
                            <span class="badge bg-warning">Programado para hoje</span>
                        {% else %}
                            <span class="badge bg-secondary">Não programado para hoje</span>
                        {% endif %}
                    </li>
                    <li><strong>Documento Edital:</strong> 
                        {% if leilao.documento_editais %}
                            <a href="{{ leilao.documento_editais.url }}" target="_blank" class="btn btn-link">Baixar Edital</a>
                        {% else %}
                            Não disponível
                        {% endif %}
                    </li>
                </ul>
            </div>
            <div class="col-md-6">
                {% if leilao.thumbnail %}
                    <img src="{{ leilao.thumbnail.url }}" alt="thumbnail do Leilão" class="img-fluid rounded shadow-lg">
                {% else %}
                    <img src="{% static 'images/leilao_default.jpg' %}" alt="thumbnail Padrão do Leilão" class="img-fluid rounded shadow-lg">
                {% endif %}
            </div>
        </div>

        <!-- Botão de Acesso ao Leilão -->
        <div class="row mt-4">
            <div class="col-md-12">
                <h3>Contagem Regressiva para o Leilão</h3>
                <div id="countdown" class="h4 mb-4"></div>
                {% if leilao.is_live %}
                    <a href="{% url 'pages:ao_vivo' leilao.codigo_leilao %}" class="btn btn-success btn-lg">Acessar Leilão Ao Vivo</a>
                {% endif %}
            </div>
        </div>

        <div class="mt-5">
            <h3 class="text-center mb-4">Itens do Leilão</h3>

            <!-- Cards de Itens -->
            <div class="row">
                {% if leilao.vehicles.exists %}
                    <div class="col-md-12 mb-4">
                        <h4 class="text-center">Veículos</h4>
                        <div class="row">
                            {% for item in leilao.vehicles.all %}
                            <div class="col-lg-4 col-md-6 mb-4">
                                <div class="card shadow-sm h-100">
                                    <img src="{{ item.thumbnail.url }}" alt="{{ item.modelo }}" class="card-img-top">
                                    <div class="card-body d-flex flex-column">
                                        <h5 class="card-title">{{ item.nome }}</h5>
                                        <p class="card-text mb-1"><strong>Ano:</strong> {{ item.fabricacao }}</p>
                                        <p class="card-text mb-1"><strong>Modelo</strong> {{ item.modelo }}</p>
                                        <p class="card-text mb-1"><strong>Marca:</strong> {{ item.marca }}</p>
                                        <p class="card-text"><strong>Preço estimado:</strong> R$ {{ item.fipe|floatformat:2 }}</p>
                                        <div class="mt-auto">
                                        <a href="{% url 'pages:item_details' item.leilao.codigo_leilao item.codigo_item %}" class="btn btn-secondary btn-block">Ver Detalhes</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}

                {% if leilao.real_estates.exists %}
                    <div class="col-md-12 mb-4">
                        <h4 class="text-center">Imóveis</h4>
                        <div class="row">
                            {% for item in leilao.real_estates.all %}
                                <div class="col-md-3 mb-4">
                                    <div class="card">
                                        {% if item.thumbnail %}
                                            <img src="{{ item.thumbnail.url }}" alt="{{ item.nome }}" class="card-img-top">
                                        {% else %}
                                            <img src="{% static 'images/default_item.jpg' %}" alt="thumbnail do Item" class="card-img-top">
                                        {% endif %}
                                        <div class="card-body">
                                            <h5 class="card-title">{{ item.nome }}</h5>
                                            <p class="card-text">{{ item.descricao }}</p>
                                            <p class="card-text"><strong>Valor Inicial:</strong> R$ {{ item.valor_inicial|floatformat:2 }}</p>
                                            <a href="#" class="btn btn-primary">Ver Detalhes</a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}

                {% if leilao.rural_items.exists %}
                    <div class="col-md-12 mb-4">
                        <h4 class="text-center">Bens Rurais</h4>
                        <div class="row">
                            {% for item in leilao.rural_items.all %}
                                <div class="col-md-3 mb-4">
                                    <div class="card">
                                        {% if item.thumbnail %}
                                            <img src="{{ item.thumbnail.url }}" alt="{{ item.nome }}" class="card-img-top">
                                        {% else %}
                                            <img src="{% static 'images/default_item.jpg' %}" alt="thumbnail do Item" class="card-img-top">
                                        {% endif %}
                                        <div class="card-body">
                                            <h5 class="card-title">{{ item.nome }}</h5>
                                            <p class="card-text">{{ item.descricao }}</p>
                                            <p class="card-text"><strong>Valor Inicial:</strong> R$ {{ item.valor_inicial|floatformat:2 }}</p>
                                            <a href="#" class="btn btn-primary">Ver Detalhes</a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}

                {% if leilao.other_goods.exists %}
                    <div class="col-md-12 mb-4">
                        <h4 class="text-center">Outros Bens</h4>
                        <div class="row">
                            {% for item in leilao.other_goods.all %}
                                <div class="col-md-3 mb-4">
                                    <div class="card">
                                        {% if item.thumbnail %}
                                            <img src="{{ item.thumbnail.url }}" alt="{{ item.nome }}" class="card-img-top">
                                        {% else %}
                                            <img src="{% static 'images/default_item.jpg' %}" alt="thumbnail do Item" class="card-img-top">
                                        {% endif %}
                                        <div class="card-body">
                                            <h5 class="card-title">{{ item.nome }}</h5>
                                            <p class="card-text">{{ item.descricao }}</p>
                                            <p class="card-text"><strong>Valor Inicial:</strong> R$ {{ item.valor_inicial|floatformat:2 }}</p>
                                            <a href="#" class="btn btn-primary">Ver Detalhes</a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}

                {% if not leilao.vehicles.exists and not leilao.real_estates.exists and not leilao.rural_items.exists and not leilao.other_goods.exists %}
                    <p class="text-center w-100">Nenhum item disponível neste leilão.</p>
                {% endif %}
            </div>
        </div>
    </div>

    {% include '_footer.html' %}

    <script>
        const countdownElement = document.getElementById('countdown');
        const targetDate = new Date("{{ leilao.date_time|date:'Y-m-d H:i:s' }}");

        function updateCountdown() {
            const now = new Date();
            const diff = targetDate - now;

            if (diff <= 0) {
                countdownElement.textContent = "Leilão iniciado!";
                document.getElementById('countdown').innerHTML = '<a href="{% url 'pages:ao_vivo' leilao.codigo_leilao %}" class="btn btn-success btn-lg">Acessar Leilão Ao Vivo</a>';
                return;
            }

            const days = Math.floor(diff / (1000 * 60 * 60 * 24));
            const hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
            const seconds = Math.floor((diff % (1000 * 60)) / 1000);

            countdownElement.textContent = `${days}d ${hours}h ${minutes}m ${seconds}s`;
        }

        setInterval(updateCountdown, 1000);
        updateCountdown(); // Atualiza imediatamente ao carregar
    </script>

</body>
</html>