categories/urls.py
# categories/urls.py
from django.urls import path
from . import views

app_name = 'categories'

urlpatterns = [
    path('imoveis/', views.imoveis, name='imoveis'),
    path('veiculos/', views.veiculos, name='veiculos'),
    path('rural/', views.rural, name='rural'),
    path('outros_bens/', views.outros_bens, name='outros_bens'),
]

gamaleiloes/urls.py
# myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),  
    path('admin/', include('admin_custom.urls')),
    path('categories/', include('categories.urls')),
    path('accounts/', include('user_management.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
# pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='home'),
    path('como-participar/', views.como_participar, name='como_participar'),
    path('leiloes_ao_vivo/', views.leiloes_ao_vivo, name='leiloes_ao_vivo'),
    path('calendario/', views.calendario, name='calendario'),
    path('leilao/<str:codigo_leilao>/<str:codigo_item>/', views.item_details, name='item_details'),
    path('leilao/<str:codigo_leilao>/ao-vivo', views.ao_vivo, name='ao_vivo'),
    path('leilao/<str:codigo_leilao>/', views.leilao_detalhe, name='leilao_detalhe'),
    path('dashboard/inicio/', views.inicio, name='inicio'),
    path('dashboard/lotes/', views.lotes, name='lotes'),
    path('dashboard/lances/', views.lances, name='lances'),
    path('financeiro/', views.financeiro_cliente, name='financeiro_cliente'),
    path('lance/<str:codigo_leilao>/<str:codigo_item>/', views.create_bid, name='create_bid'),
]

templates/_footer.html
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- Font Awesome for social media icons -->
<script src="https://kit.fontawesome.com/a076d05399.js"></script>

<footer class="footer">
  <div class="container p-5 bg-dark text-white text-center text-lg-start mt-4">
    <div class="row">
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">Gama Leilões</h5>
        <p>
          Proporcionando a melhor experiência de leilão. Dê seus lances, vença e aproveite itens exclusivos.
        </p>
      </div>
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Links</h5>
        <ul class="list-unstyled mb-0">
          <li><a href="{% url 'pages:home' %}" class="text-white">Página Inicial</a></li>
          <li><a href="{% url 'pages:calendario' %}" class="text-white">Leilões</a></li>
          <li><a href="{% url 'pages:como_participar' %}" class="text-white">Como participar</a></li>
        </ul>
      </div>
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Contato</h5>
        <ul class="list-unstyled mb-0">
          <li><a href="mailto:suporte@gamaleiloes.com" class="text-white">Envie um Email</a></li>
          <li><a href="" class="text-white">Suporte</a></li>
          <li><a href="" class="text-white">FAQ</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); font-size: 0.9rem;">
    Davi S. Santos JUCESP n.°1483 - Todos os direitos reservados à Gama Leilões ©
  </div>
</footer>

templates/_head.html
{% load static %}
<head>
  <title>Gama Leilões</title>
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
  />
  <link rel="stylesheet" href="{% static 'pages/css/styles.css' %}" />
  <link rel="stylesheet" href="{% static 'css/general.css' %}" />
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://stackpath.bootstrap.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>  
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
</head>

templates/_header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'pages:home' %}">
        <img src="{% static 'pages/img/logo.png' %}" alt="Logo">
    </a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <form class="form-inline search-bar ml-auto">
            <input class="form-control mr-sm-2 search-nav" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Pesquisar</button>
        </form>
        <div class="ml-3">
            {% if user.is_authenticated %}
                <form id="logout-form" method="post" action="{% url 'account_logout' %}" style="display: none;">
                    {% csrf_token %}
                </form>
                <button class="btn btn-secondary" onclick="document.getElementById('logout-form').submit();">Sair</button>
                <a class="btn btn-outline-secondary ml-2" href="{% url 'account_profile' %}">Minha Conta</a>
            {% else %}
                <a class="btn btn-outline-secondary" href="{% url 'account_login' %}">Entrar</a>
                <a class="btn btn-secondary ml-2" href="{% url 'account_signup' %}">Cadastrar</a>
            {% endif %}
        </div>
    </div>
</nav>
<nav class="navbar navbar-expand-lg mt-2" id="links">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav2" aria-controls="navbarNav2" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav2"> 
        <ul class="navbar-nav mx-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:home' %}" style="transition: color 0.3s; color:#fff;">Página Inicial</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="leiloesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="transition: color 0.3s;color:#fff;">
                    Leilões
                </a>
                <div class="dropdown-menu" aria-labelledby="leiloesDropdown">
                    <a class="dropdown-item" href="{% url 'pages:leiloes_ao_vivo' %}">Leilões Ao Vivo</a>
                    <a class="dropdown-item" href="{% url 'pages:calendario' %}">Calendário</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:como_participar' %}" style="transition: color 0.3s;color:#fff;">Como Participar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories:imoveis' %}" style="transition: color 0.3s; color:#fff;">Imóveis</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories:veiculos' %}" style="transition: color 0.3s; color:#fff;">Veículos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories:rural' %}" style="transition: color 0.3s; color:#fff;">Rural</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories:outros_bens' %}" style="transition: color 0.3s; color:#fff;">Outros Bens</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="" id="dashboardDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="transition: color 0.3s;color:#fff;">
                        Dashboard
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dashboardDropdown">
                        <a class="dropdown-item" href="{% url 'pages:inicio' %}">Início</a>
                        <a class="dropdown-item" href="{% url 'pages:lotes' %}">Lotes</a>
                        <a class="dropdown-item" href="{% url 'pages:lances' %}">Lances</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:financeiro_cliente' %}" style="transition: color 0.3s; color:#fff;">Financeiro</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include '_head.html' %} <!-- Inclui o parcial do head -->
    <title>{% block head_title %}Gama Leilões{% endblock head_title %}</title>
    {% block extra_head %}{% endblock extra_head %}
</head>
<body>
    {% include '_header.html' %} <!-- Inclui o parcial do header -->

    <main class="container">
        {% block content %}{% endblock content %}
    </main>

    {% include '_footer.html' %} <!-- Inclui o parcial do footer -->
    
    {% block extra_body %}{% endblock extra_body %}
</body>
</html>